/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        gray: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
        },
        danger: {
          50: 'var(--color-danger-50)',
          100: 'var(--color-danger-100)',
          300: 'var(--color-danger-300)',
          400: 'var(--color-danger-400)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
          800: 'var(--color-danger-800)',
        },
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
        },
        accent: {
          50: 'var(--color-accent-50)',
          100: 'var(--color-accent-100)',
          500: 'var(--color-accent-500)',
          600: 'var(--color-accent-600)',
          700: 'var(--color-accent-700)',
          800: 'var(--color-accent-800)',
        },
        info: {
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          600: 'var(--color-info-600)',
          800: 'var(--color-info-800)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          subtle: 'var(--color-surface-subtle)',
          muted: 'var(--color-surface-muted)',
        },
        foreground: {
          DEFAULT: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          subtle: 'var(--color-text-subtle)',
          inverse: 'var(--color-text-inverse)',
        },
        onPrimary: 'var(--color-text-on-primary)',
        border: {
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
        },
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        14: 'var(--space-14)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
        40: 'var(--space-40)',
        48: 'var(--space-48)',
        56: 'var(--space-56)',
        64: 'var(--space-64)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
      },
      fontSize: {
        xs: ['var(--font-size-caption)', { lineHeight: 'var(--line-height-normal)' }],
        sm: ['var(--font-size-body-sm)', { lineHeight: 'var(--line-height-normal)' }],
        base: ['var(--font-size-body)', { lineHeight: 'var(--line-height-normal)' }],
        lg: ['var(--font-size-section)', { lineHeight: 'var(--line-height-snug)' }],
        xl: ['var(--font-size-title)', { lineHeight: 'var(--line-height-snug)' }],
        '2xl': ['var(--font-size-title-lg)', { lineHeight: 'var(--line-height-tight)' }],
        '3xl': ['var(--font-size-title-lg)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl': ['var(--font-size-title-lg)', { lineHeight: 'var(--line-height-tight)' }],
        title: ['var(--font-size-title)', { lineHeight: 'var(--line-height-snug)' }],
        'title-lg': ['var(--font-size-title-lg)', { lineHeight: 'var(--line-height-tight)' }],
        section: ['var(--font-size-section)', { lineHeight: 'var(--line-height-snug)' }],
        body: ['var(--font-size-body)', { lineHeight: 'var(--line-height-normal)' }],
        'body-sm': ['var(--font-size-body-sm)', { lineHeight: 'var(--line-height-normal)' }],
        caption: ['var(--font-size-caption)', { lineHeight: 'var(--line-height-normal)' }],
      },
    },
  },
  plugins: [],
}
