import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import ReportFooter from '../ReportFooter'

describe('ReportFooter', () => {
  it('생성 정보와 기밀 문구를 표시해야 한다', () => {
    render(
      <ReportFooter
        footerText="Generated by Go Almond AI Engine v2.4. Protected under Digital IP Policy."
        pageLabel="CONFIDENTIAL - PAGE 01/01"
      />
    )

    expect(screen.getByText(/Generated by Go Almond AI Engine/i)).toBeInTheDocument()
    expect(screen.getByText('CONFIDENTIAL - PAGE 01/01')).toBeInTheDocument()
  })
})
