import type {
  IndicatorScores,
  MatchingResponse,
  MatchingResultItem,
  NextStepItem,
  ReportMeta,
  TopMatchExtras,
} from '../types/matching'

const formatReportDate = (rawDate?: string): string => {
  const base = rawDate ? new Date(rawDate) : new Date()
  if (Number.isNaN(base.getTime())) {
    return new Date().toISOString().slice(0, 10).replaceAll('-', '.')
  }
  const year = base.getFullYear()
  const month = String(base.getMonth() + 1).padStart(2, '0')
  const day = String(base.getDate()).padStart(2, '0')
  return `${year}.${month}.${day}`
}

export const buildReportMeta = (result: MatchingResponse): ReportMeta => {
  const createdAt = new Date(result.created_at)
  const year = Number.isNaN(createdAt.getTime()) ? new Date().getFullYear() : createdAt.getFullYear()
  const suffix = result.matching_id?.slice(0, 6)?.toUpperCase() || '000000'
  return {
    refId: `GA-${year}-MATCH-${suffix}`,
    date: formatReportDate(result.created_at),
    userLabel: result.user_id || 'Guest',
  }
}

export const buildIndicatorScores = (
  item: MatchingResultItem | undefined
): IndicatorScores => {
  if (!item) {
    return { academicFit: 0, careerOutlook: 0, costEfficiency: 0 }
  }

  const { academic, english, career, location, budget, duration } = item.score_breakdown
  return {
    academicFit: Math.round((academic + english) / 2),
    careerOutlook: Math.round((career + location) / 2),
    costEfficiency: Math.round((budget + duration) / 2),
  }
}

export const buildExecutiveSummary = (
  item: MatchingResultItem | undefined,
  totalMatches: number
): string => {
  if (!item) {
    return 'We analyzed your profile to deliver personalized school recommendations.'
  }
  return `Based on your profile, we evaluated ${totalMatches} matches and identified ${item.school.name} (${item.program.name}) as the best fit.`
}

export const matchingReportMock = {
  footerText: 'Generated by Go Almond AI Engine v2.4. Protected under Digital IP Policy.',
  pageLabel: 'CONFIDENTIAL - PAGE 01/01',
  indicatorDescription:
    'Your strongest alignment appears in academic fit and career outlook, with budget considerations optimized for ROI.',
  topMatchExtras: {
    estimatedRoi: '12.5%',
    averageSalary: '$85,000',
    globalRanking: '#4 (Computer Science)',
    alumniNetwork: '38,000+',
    featureBadges: ['OPT STEM ELIGIBLE', 'ON-CAMPUS HOUSING', 'INDUSTRY PARTNERSHIPS'],
  } satisfies TopMatchExtras,
  nextSteps: [
    {
      id: 1,
      title: 'Document Audit',
      description: 'Upload your GPA and test scores for final review.',
    },
    {
      id: 2,
      title: 'SOP Workshop',
      description: 'Schedule session with our specialized editors.',
    },
    {
      id: 3,
      title: 'Portal Access',
      description: 'Go Almond will open your common app dashboard.',
    },
    {
      id: 4,
      title: 'Visa Prep',
      description: 'Start I-20 documentation and interview training.',
    },
  ] satisfies NextStepItem[],
}
